# Generated by Django 5.1.6 on 2025-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(default='ktm', max_length=255),
            preserve_default=False,
        ),
    ]
